PRIMITIVE_HOLD = "hold"
PRIMITIVE_GLANCE_LEFT = "glance_left"
PRIMITIVE_GLANCE_RIGHT = "glance_right"
PRIMITIVE_ACKNOWLEDGE = "acknowledge"
PRIMITIVE_BREATH = "breath"

ALL_PRIMITIVES = {
    PRIMITIVE_HOLD,
    PRIMITIVE_GLANCE_LEFT,
    PRIMITIVE_GLANCE_RIGHT,
    PRIMITIVE_ACKNOWLEDGE,
    PRIMITIVE_BREATH,
}
