#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${HOME}/.config/pala/env.sh"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    -h|--help)
      cat <<'EOF'
Usage: tools/pala_env_wizard.sh [--env-file PATH]

Interactive wizard to set PALA model/provider environment variables.
It writes exports to an env file (default: ~/.config/pala/env.sh).
EOF
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

mkdir -p "$(dirname "$ENV_FILE")"
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

mask_secret() {
  local value="$1"
  local len=${#value}
  if [[ $len -eq 0 ]]; then
    printf "(empty)"
    return
  fi
  if [[ $len -le 8 ]]; then
    printf "%*s" "$len" "" | tr ' ' '*'
    return
  fi
  printf "%s...%s" "${value:0:4}" "${value: -4}"
}

shell_escape() {
  printf "%s" "$1" | sed "s/'/'\"'\"'/g"
}

show_var() {
  local var_name="$1"
  local is_secret="${2:-0}"
  local value="${!var_name-}"
  if [[ "$is_secret" == "1" ]]; then
    printf "  %-24s = %s\n" "$var_name" "$(mask_secret "$value")"
  else
    if [[ -z "$value" ]]; then
      printf "  %-24s = (empty)\n" "$var_name"
    else
      printf "  %-24s = %s\n" "$var_name" "$value"
    fi
  fi
}

choose_value() {
  local var_name="$1"
  local label="$2"
  shift 2
  local current="${!var_name-}"
  local options=("$@")

  echo
  echo "${label}"
  if [[ -n "$current" ]]; then
    echo "Current: $current"
  else
    echo "Current: (empty)"
  fi
  local i=1
  for opt in "${options[@]}"; do
    echo "  ${i}) ${opt}"
    i=$((i + 1))
  done
  echo "  c) custom"
  echo "  k) keep current"
  echo "  x) clear"
  read -r -p "Choose: " pick

  if [[ "$pick" == "k" || "$pick" == "K" ]]; then
    return
  fi
  if [[ "$pick" == "x" || "$pick" == "X" ]]; then
    printf -v "$var_name" "%s" ""
    return
  fi
  if [[ "$pick" == "c" || "$pick" == "C" ]]; then
    local custom=""
    read -r -p "Enter ${var_name}: " custom
    printf -v "$var_name" "%s" "$custom"
    return
  fi
  if [[ "$pick" =~ ^[0-9]+$ ]]; then
    local idx=$((pick - 1))
    if [[ $idx -ge 0 && $idx -lt ${#options[@]} ]]; then
      printf -v "$var_name" "%s" "${options[$idx]}"
      return
    fi
  fi
  echo "Invalid choice. Keeping current value."
}

choose_secret() {
  local var_name="$1"
  local label="$2"
  local current="${!var_name-}"
  echo
  echo "${label}"
  echo "Current: $(mask_secret "$current")"
  echo "  1) keep current"
  echo "  2) enter new value"
  echo "  3) clear"
  read -r -p "Choose: " pick
  case "$pick" in
    1) return ;;
    2)
      local secret=""
      read -r -s -p "Enter ${var_name}: " secret
      echo
      printf -v "$var_name" "%s" "$secret"
      ;;
    3)
      printf -v "$var_name" "%s" ""
      ;;
    *)
      echo "Invalid choice. Keeping current value."
      ;;
  esac
}

echo "PALA Environment Wizard"
echo "Env file: ${ENV_FILE}"
echo
echo "Current values:"
show_var "PALA_MODEL_PROVIDER"
show_var "PALA_COSMOS_PROVIDER"
show_var "PALA_COSMOS_BASE_URL"
show_var "PALA_COSMOS_MODEL"
show_var "PALA_COSMOS_API_KEY" 1
show_var "PALA_COSMOS_PROMPT"
show_var "PALA_LOG_LEVEL"
show_var "PALA_MAX_RUNTIME_S"

choose_value "PALA_MODEL_PROVIDER" "Select provider" "auto" "cosmos" "gemini" "openai"
PALA_COSMOS_PROVIDER="${PALA_MODEL_PROVIDER-}"

if [[ "${PALA_MODEL_PROVIDER-}" == "gemini" ]]; then
  choose_value "PALA_COSMOS_BASE_URL" "Select base URL" \
    "https://generativelanguage.googleapis.com/v1beta/openai" \
    "https://generativelanguage.googleapis.com"
  choose_value "PALA_COSMOS_MODEL" "Select model" \
    "gemini-2.5-flash-lite" \
    "gemini-2.5-flash" \
    "gemini-3-flash-preview" \
    "gemini-2.5-flash-lite-preview-06-17" \
    "gemini-2.5-pro"
else
  choose_value "PALA_COSMOS_BASE_URL" "Select base URL" \
    "http://127.0.0.1:8000" \
    "http://localhost:8000" \
    "http://160.211.46.144:8000"
  choose_value "PALA_COSMOS_MODEL" "Select model" \
    "nvidia/cosmos-reason2-2b" \
    "nvidia/cosmos-reason2-8b"
fi

choose_secret "PALA_COSMOS_API_KEY" "API key"
choose_value "PALA_COSMOS_PROMPT" "Planner prompt preset" \
  "Prioritize calm, safe desk-companion behavior. Always choose one concrete next action." \
  "Keep responses terse and actionable. Prefer meaningful orient_to_zone/glance over hold." \
  "Maintain calm social presence; acknowledge people with subtle movement."
choose_value "PALA_LOG_LEVEL" "Log level" "INFO" "DEBUG" "WARNING" "ERROR"
choose_value "PALA_MAX_RUNTIME_S" "Max runtime seconds (blank = unlimited)" "30" "60" "120"

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by tools/pala_env_wizard.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  for var_name in \
    PALA_MODEL_PROVIDER \
    PALA_COSMOS_PROVIDER \
    PALA_COSMOS_BASE_URL \
    PALA_COSMOS_MODEL \
    PALA_COSMOS_API_KEY \
    PALA_COSMOS_PROMPT \
    PALA_LOG_LEVEL \
    PALA_MAX_RUNTIME_S; do
    value="${!var_name-}"
    if [[ -n "${value}" ]]; then
      echo "export ${var_name}='$(shell_escape "$value")'"
    else
      echo "unset ${var_name}"
    fi
  done
} > "${ENV_FILE}"

echo
echo "Saved ${ENV_FILE}"
echo "Apply now with:"
echo "  source \"${ENV_FILE}\""
